title: Cloning the Goose
author: Aidan Boyd
description: A blog about supercharging personal productivity with AI tools and workflows
remote_theme: jekyll/minima
minima:
  skin: solarized-dark
plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-seo-tag